spring.application.name=dashboard

# --- BDD, spring sabe que tiene que usar H2 y guardar los datos en el archivo dashboard.mv.db ---
spring.datasource.url=jdbc:h2:file:./data/dashboard;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa

# --- Creamos las tablas si no existen de la BDD y las actualiza ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# --- Con esto evitamos que se corte la conexion del SSE ---
spring.mvc.async.request-timeout=-1
